### ISSUE TITLE
课程二：Java线程状态转移图

### ISSUE THREAD

**Issue by fatpo** [fatpo/fatpo.github.io#3]
https://fatpo.github.io/#/%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B/%E7%BA%BF%E7%A8%8B/%E8%AF%BE%E7%A8%8B%E4%BA%8C%EF%BC%9AJava%E7%BA%BF%E7%A8%8B%E7%8A%B6%E6%80%81%E8%BD%AC%E7%A7%BB%E5%9B%BE 

 Description

**Comment by fatpo** [comment]
请注意好 java 和 linux 的线程区别~ 务必先看linux的线程状态转移图！

**Comment by fatpo** [comment]
国哥能详细讲解下wait()方法吗,为啥线程A调用对象B.wait()方法,会释放对象B锁,并进入等待队列吗

---

要知道wait方法，并不是释放B的锁（B此时此刻还在执行！！！），而是A释放锁后进入WAITING状态，A在等B！！！A在等待队列中。

**Comment by zhanLi1212** [comment]
> @fatpo
> 国哥能详细讲解下wait()方法吗,为啥线程A调用对象B.wait()方法,会释放对象B锁,并进入等待队列吗
> 
> ---
> 
> 要知道wait方法，并不是释放B的锁（B此时此刻还在执行！！！），而是A释放锁后进入WAITING状态，A在等B！！！A在等待队列中。

**Comment by zhanLi1212** [comment]
我是理解为释放了B的锁啊,但是理解的还是不够透彻,想不明白为啥B .wait()为啥不是B 进入WAITING状态,而是A反而去等B

**Comment by fatpo** [comment]
> @zhanLi1212
> 我是理解为释放了B的锁啊,但是理解的还是不够透彻,想不明白为啥B .wait()为啥不是B 进入WAITING状态,而是A反而去等B

1、我先个举个例子让你理解下，你（A）让张三（B）帮你跑个腿，你在原地站着不动，是不是你在等待状态，而张三此时此刻欢快的奔跑在路上。所以一样的，进入WAITING状态是A，而不是B。
2、java线程也是如此，线程B是有任务在执行的，它占用了CPU处理器执行指令，线程A此时此刻无法继续执行执行，当然要让出CPU啊，它让出CPU后进入了等待队列，坐等B执行完毕。
3、至于锁不锁，锁其实和线程没太大关系，锁和对象有关系，唯一的有点关系就是对象的头markword记录了线程ID。所以不是释放了B的锁，是A释放了某个临界资源（一般是object）的锁，然后进入了等待队列。

**Comment by zhanLi1212** [comment]
也就是说wait()释放锁后A和B线程变成了相互争夺CPUl是吧

**Comment by fatpo** [comment]
> @zhanLi1212
> 也就是说wait()释放锁后A和B线程变成了相互争夺CPUl是吧

不是，只有线程B在用CPU，A不抢。线程A释放锁后，它处于WAITING状态，不会争抢CPU，只有READY状态的线程才会抢CPU，RUNNING状态正在用CPU。

**Comment by zhanLi1212** [comment]
线程1：进入临界方法区！！！1 ms
线程2：等待进入临界方法区！！！1 ms
线程1：在执行前半段代码，cnt：38912
线程1：执行wait()
线程2：终于进入临界区，之前等待了锁：494 ms
线程2：唤起发出信号，让线程1继续执行...
当前线程:线程2
线程1：在执行后半段代码
线程2：执行后半段，cnt：1
线程1：执行后半段，cnt：1

**Comment by zhanLi1212** [comment]
我又理解错了吗.这两个线程不会再相互执行吗

**Comment by fatpo** [comment]
> @zhanLi1212
> 我又理解错了吗.这两个线程不会再相互执行吗
> 

这次没理解错呢，线程1和线程2是交叉执行的。你看日志也能看出来~

**Comment by zhanLi1212** [comment]
交叉执行为啥不是在争夺cpu

**Comment by fatpo** [comment]
> @zhanLi1212
> 交叉执行为啥不是在争夺cpu

这里交叉执行，但是你注意线程A，是它主动放弃CPU占用，从RUNNIGN状态释放锁进入WAITING状态。它并没有和线程B争抢。如果此时此刻有两个READY状态线程，他们才是争抢CPU，为了防止无规则争抢，就有很多调度算法，比如时间片轮流、比如优先级争抢。你先看看JAVA线程状态流状图的 READY <---> RUNNING，里面就有dispatch，就是调度。线程A从WAITING恢复后，是进入READY队列，那个时候才会争抢CPU。

**Comment by zhanLi1212** [comment]
> @fatpo
> > @zhanLi1212
> > 交叉执行为啥不是在争夺cpu
> 
> 这里交叉执行，但是你注意线程A，是它主动放弃CPU占用，从RUNNIGN状态释放锁进入WAITING状态。它并没有和线程B争抢。如果此时此刻有两个READY状态线程，他们才是争抢CPU，为了防止无规则争抢，就有很多调度算法，比如时间片轮流、比如优先级争抢。你先看看JAVA线程状态流状图的 READY <---> RUNNING，里面就有dispatch，就是调度。线程A从WAITING恢复后，是进入READY队列，那个时候才会争抢CPU。

理解了
